---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 10
    target-branch: "release"
    commit-message:
      prefix: "chore"

  - package-ecosystem: "docker"
    directory: "/ldnmp/openresty/stable"
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 10
    target-branch: "release"
    commit-message:
      prefix: "ldnmp"

  - package-ecosystem: "docker"
    directory: "/ldnmp/openresty/edge"
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 10
    target-branch: "release"
    commit-message:
      prefix: "ldnmp"
