---
name: "Build and Publish frp"

on:
  schedule:
    - cron: "0 16 * * 3,6"
  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  DOCKER_USERNAME: ${{ github.repository_owner }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    name: "Build and Publish frp"
    runs-on: ubuntu-latest
    outputs:
      pushed: ${{ steps.bump_version.outputs.build_image }}

    steps:
      - name: "Check out repository"
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0

      - name: "Fetch Versions and Determine Build"
        id: bump_version
        run: |
          FRP_LVER="$(wget -qO- --tries=50 --header="Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/fatedier/frp/releases/latest | grep '"tag_name":' | sed -n 's/.*"tag_name": "[^0-9]*\([0-9.]*\)".*/\1/p')"
          FRP_CVER="$(wget -qO- --tries=50 https://hub.docker.com/v2/repositories/$DOCKER_USERNAME/frp/tags 2>/dev/null | grep -o '"name":"[^"]*"' | awk -F'"' '$4!="latest"{print $4}' | sort -Vr | head -n1 || true)"
          echo "frp_version=${FRP_LVER}" >> "$GITHUB_OUTPUT"
          if [[ "$(printf '%s\n%s\n' "$FRP_LVER" "$FRP_CVER" | sort -V | head -n1)" != "$FRP_LVER" || -z "$FRP_CVER" && -n "$FRP_LVER" ]]; then
            echo "build_image=1" >> "$GITHUB_OUTPUT"
          fi

      - name: "Set up Docker QEMU"
        if: steps.bump_version.outputs.build_image == '1' || github.event_name == 'workflow_dispatch'
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3.7.0

      - name: "Set up Docker Buildx"
        if: steps.bump_version.outputs.build_image == '1' || github.event_name == 'workflow_dispatch'
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0

      - name: "Login to DockerHub"
        if: steps.bump_version.outputs.build_image == '1' || github.event_name == 'workflow_dispatch'
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: "Extract Docker metadata"
        if: steps.bump_version.outputs.build_image == '1' || github.event_name == 'workflow_dispatch'
        id: meta
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5.10.0
        with:
          images: ${{ env.DOCKER_USERNAME }}/frp
          tags: |
            type=raw,value=${{ steps.bump_version.outputs.frp_version }}
            type=raw,value=latest
          labels: |
            org.opencontainers.image.description=A fast reverse proxy to help you expose a local server behind a NAT or firewall to the internet.
            org.opencontainers.image.source=https://github.com/fatedier/frp
            org.opencontainers.image.title=FRP
            org.opencontainers.image.url=https://gofrp.org

      - name: "Build and Push frp image"
        if: steps.bump_version.outputs.build_image == '1' || github.event_name == 'workflow_dispatch'
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: ${{ github.workspace }}/forge/frp
          file: ${{ github.workspace }}/forge/frp/Dockerfile
          platforms: linux/amd64, linux/arm64/v8
          build-args: FRP_VERSION=${{ steps.bump_version.outputs.frp_version }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: ${{ github.event_name != 'pull_request' }}

  sync:
    name: "Sync readme to dockerhub"
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - name: "Check out repository"
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0

      - name: "Sync readme to dockerhub"
        if: needs.build.outputs.pushed == '1' || github.event_name == 'workflow_dispatch'
        uses: peter-evans/dockerhub-description@1b9a80c056b620d92cedb9d9b5a223409c68ddfa # v5.0.0
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
          repository: ${{ env.DOCKER_USERNAME }}/frp
          readme-filepath: ${{ github.workspace }}/forge/frp/README.md
          enable-url-completion: false
