---
name: 'Build and Publish kms'

on:
  schedule:
    - cron: '0 16 1 * *'
  workflow_dispatch:

jobs:
  build:
    name: 'Build and Publish kms'
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: 'Set up Docker QEMU'
        uses: docker/setup-qemu-action@v3.6.0

      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v3.10.0

      - name: 'Login to DockerHub'
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: 'Build and push kms image'
        uses: docker/build-push-action@v6.18.0
        with:
          context: ${{ github.workspace }}/forge/kms
          file: ${{ github.workspace }}/forge/kms/Dockerfile
          platforms: linux/386, linux/amd64, linux/arm/v6, linux/arm/v7, linux/arm64/v8, linux/ppc64le, linux/riscv64, linux/s390x
          tags: "${{ env.DOCKER_USERNAME }}/kms:latest"
          push: true