---
name: "GitHub Actions Mirror"

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  mirror2cnb:
    name: "Mirror to cnb"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: "Mirror to cnb"
        uses: honeok/git-mirror-repository-action@v1
        with:
          REMOTE: https://cnb.cool/${{ github.repository }}.git
          GIT_USERNAME: cnb
          GIT_PASSWORD: ${{ secrets.SYNC_CNB_TOKEN }}
          GIT_SSH_NO_VERIFY_HOST: true
          PUSH_ALL_REFS: false

  mirror2framagit:
    name: "Mirror to framagit"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: "Mirror to framagit"
        uses: honeok/git-mirror-repository-action@v1
        with:
          REMOTE: git@framagit.org:${{ github.repository }}.git
          GIT_SSH_PRIVATE_KEY: ${{ secrets.SYNC_PRIVATE_KEY }}
          GIT_SSH_NO_VERIFY_HOST: true
          PUSH_ALL_REFS: false

  mirror2codeberg:
    name: "Mirror to codeberg"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: "Mirror to codeberg"
        uses: honeok/git-mirror-repository-action@v1
        with:
          REMOTE: git@codeberg.org:${{ github.repository }}.git
          GIT_SSH_PRIVATE_KEY: ${{ secrets.SYNC_PRIVATE_KEY }}
          GIT_SSH_NO_VERIFY_HOST: true
          PUSH_ALL_REFS: false
