---
name: "Build Nginx"

on:
  push:
    branches:
      - master
    paths:
      - "ldnmp/nginx/**"
      - "!ldnmp/nginx/**.md"
  schedule:
    - cron: "0 16 * * 3,6"
  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    name: "Build and Publish Nginx"
    runs-on: ubuntu-latest
    outputs:
      pushed: ${{ steps.bump_version.outputs.build_image }}

    steps:
      - name: "Check out repository"
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: "Fetch Versions and Determine Build"
        id: bump_version
        run: |
          NGX_LVER="$(wget -qO- --tries=50 --header="Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/nginx/nginx/releases/latest | grep '"tag_name":' | sed -n 's/.*"tag_name": "[^0-9]*\([0-9.]*\)".*/\1/p')"
          NGX_CVER="$(wget -qO- --tries=50 https://hub.docker.com/v2/repositories/honeok/nginx/tags 2>/dev/null | grep -o '"name":"[^"]*"' | awk -F'"' '{print $4}' | grep -E -- '-alpine$' | sort -rV | head -n1 | sed 's/-alpine$//' || true)"
          NGX_IMG_LVER="$(docker run --rm nginx:${NGX_LVER}-alpine sh -c "nginx -v 2>&1" 2>/dev/null | awk -F'[/ ]' '{print $NF}' || true)"
          ACME_LVER="$(wget -qO- --tries=50 --header="Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/nginx/nginx-acme/releases/latest | grep '"tag_name":' | sed -n 's/.*"tag_name": "[^0-9]*\([0-9.]*\)".*/\1/p')"
          ZSTD_LVER="$(wget -qO- --tries=50 --header="Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/facebook/zstd/releases/latest | grep '"tag_name":' | sed -n 's/.*"tag_name": "[^0-9]*\([0-9.]*\)".*/\1/p')"
          HEADERS_MORE_LTAG="$(wget -qO- --tries=50 --header="Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/openresty/headers-more-nginx-module/tags | sed -n 's/.*"name": "v\?\([0-9][0-9.]*\)".*/\1/p' | sort -rV | head -n1)"
          echo "ngx_version=${NGX_LVER}" >> "$GITHUB_OUTPUT"
          echo "acme_version=${ACME_LVER}" >> "$GITHUB_OUTPUT"
          echo "zstd_version=${ZSTD_LVER}" >> "$GITHUB_OUTPUT"
          echo "headers_more_tag=${HEADERS_MORE_LTAG}" >> "$GITHUB_OUTPUT"
          if [[ "$(printf '%s\n%s\n' "$NGX_LVER" "$NGX_CVER" | sort -V | head -n1)" != "$NGX_LVER" && "$NGX_IMG_LVER" == "$NGX_LVER" || -z "$NGX_CVER" && "$NGX_IMG_LVER" == "$NGX_LVER" ]]; then
            echo "build_image=1" >> "$GITHUB_OUTPUT"
          fi

      - name: "Set up Docker QEMU"
        if: steps.bump_version.outputs.build_image == '1' || github.event_name == 'workflow_dispatch'
        uses: docker/setup-qemu-action@v3

      - name: "Set up Docker Buildx"
        if: steps.bump_version.outputs.build_image == '1' || github.event_name == 'workflow_dispatch'
        uses: docker/setup-buildx-action@v3

      - name: "Login to DockerHub"
        if: steps.bump_version.outputs.build_image == '1' || github.event_name == 'workflow_dispatch'
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: "Extract Docker metadata"
        if: steps.bump_version.outputs.build_image == '1' || github.event_name == 'workflow_dispatch'
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_USERNAME }}/nginx
          tags: |
            type=raw,value=alpine
            type=raw,value=${{ steps.bump_version.outputs.ngx_version }}-alpine
          labels: |
            org.opencontainers.image.description=nginx is an HTTP web server, reverse proxy, content cache, load balancer, TCP/UDP proxy server, and mail proxy server.
            org.opencontainers.image.source=https://github.com/nginx/nginx
            org.opencontainers.image.title=Nginx
            org.opencontainers.image.url=https://nginx.org

      - name: "Build and Push Nginx image"
        if: steps.bump_version.outputs.build_image == '1' || github.event_name == 'workflow_dispatch'
        uses: docker/build-push-action@v6
        with:
          context: ${{ github.workspace }}/ldnmp/nginx
          file: ${{ github.workspace }}/ldnmp/nginx/Dockerfile
          platforms: linux/amd64, linux/arm64/v8
          build-args: |
            NGX_VERSION=${{ steps.bump_version.outputs.ngx_version }}
            ACME_VERSION=${{ steps.bump_version.outputs.acme_version }}
            ZSTD_VERSION=${{ steps.bump_version.outputs.zstd_version }}
            HEADERS_MORE_TAG=${{ steps.bump_version.outputs.headers_more_tag }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: ${{ github.event_name != 'pull_request' }}

  sync:
    name: "Sync readme to dockerhub"
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - name: "Check out repository"
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: "Sync readme to dockerhub"
        if: needs.build.outputs.pushed == '1' || github.event_name == 'workflow_dispatch'
        uses: peter-evans/dockerhub-description@v5
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
          repository: ${{ env.DOCKER_USERNAME }}/nginx
          readme-filepath: ${{ github.workspace }}/ldnmp/nginx/README.md
          enable-url-completion: false
