---
name: "Build and Publish PHP"

on:
  schedule:
    - cron: "0 16 * * 3,6"
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    name: "Build and Publish PHP"
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ github.repository_owner }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: "Check out repository"
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0

      - name: "Fetch Versions and Determine Build"
        id: bump_version
        run: |
          PHP_LVER="$(wget -qO- --tries=50 --header="Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/php/php-src/releases/latest | grep '"tag_name":' | sed -n 's/.*"tag_name": "[^0-9]*\([0-9.]*\)".*/\1/p')"
          PHP_CVER="$(wget -qO- --tries=50 https://hub.docker.com/v2/repositories/honeok/php/tags 2>/dev/null | grep -o '"name":"[^"]*"' | awk -F'"' '{print $4}' | grep -E '^[0-9]+\.[0-9]+\.[0-9]+' | sort -Vr | head -n1 | sed 's/^\([0-9]\+\.[0-9]\+\.[0-9]\+\).*/\1/' || true)"
          PHP_IMG_LVER="$(docker run --rm php:${PHP_LVER}-fpm-alpine sh -c 'php -v 2>&1' 2>/dev/null | awk '/^PHP/ {print $2; exit}' || true)"
          echo "php_version=${PHP_LVER}" >> "$GITHUB_OUTPUT"
          if [[ "$(printf '%s\n%s\n' "$PHP_LVER" "$PHP_CVER" | sort -V | head -n1)" != "$PHP_LVER" && "$PHP_IMG_LVER" == "$PHP_LVER" || -z "$PHP_CVER" && "$PHP_IMG_LVER" == "$PHP_LVER" ]]; then
            echo "build_image=1" >> "$GITHUB_OUTPUT"
          fi

      - name: "Set up Docker QEMU"
        if: steps.bump_version.outputs.build_image == '1' || github.event_name == 'workflow_dispatch'
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3.7.0

      - name: "Set up Docker Buildx"
        if: steps.bump_version.outputs.build_image == '1' || github.event_name == 'workflow_dispatch'
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0

      - name: "Login to DockerHub"
        if: steps.bump_version.outputs.build_image == '1' || github.event_name == 'workflow_dispatch'
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: "Extract Docker metadata"
        if: steps.bump_version.outputs.build_image == '1' || github.event_name == 'workflow_dispatch'
        id: meta
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5.10.0
        with:
          images: ${{ env.DOCKER_USERNAME }}/php
          tags: |
            type=raw,value=fpm-alpine
            type=raw,value=${{ steps.bump_version.outputs.php_version }}-fpm-alpine
          labels: |
            org.opencontainers.image.description=PHP is a popular general-purpose scripting language that is especially suited to web development. Fast, flexible and pragmatic, PHP powers everything from your blog to the most popular websites in the world.
            org.opencontainers.image.source=https://github.com/php/php-src
            org.opencontainers.image.title=PHP
            org.opencontainers.image.url=https://www.php.net

      - name: "Build and Push PHP image"
        if: steps.bump_version.outputs.build_image == '1' || github.event_name == 'workflow_dispatch'
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: ${{ github.workspace }}/ldnmp/php
          file: ${{ github.workspace }}/ldnmp/php/Dockerfile
          platforms: linux/amd64, linux/arm64
          build-args: PHP_VERSION=${{ steps.bump_version.outputs.php_version }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: ${{ github.event_name != 'pull_request' }}
